# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d42a7613b2b43edd8ffb0ce8f7333dac3331d37af0ecc354a66183abaf976c35e8a494891195a7f5a8a7196032c06b523ab50897294bf6364378245b858a503

test:
  secret_key_base: a4a561d936f728c4632d1184e9840bc3e0fc878afc26f9e79f86408f205276387aa0b705ffa22ce442533dd8f5250703438091640918f2f33a849ee41276435a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
